### ISSUE TITLE
Restore Code Climate

### ISSUE THREAD

**Issue by PowerKiKi** [jbox-web/gitolite-rugged#10]
@n-rodriguez, please revert 3251bd64163ce01b42db70b0462340ee96d865fd and add the [`CC_TEST_REPORTER_ID`](https://docs.codeclimate.com/docs/finding-your-test-coverage-token), as discussed in https://github.com/jbox-web/gitolite-rugged/pull/8#issuecomment-1260961668.

Or alternatively share the `CC_TEST_REPORTER_ID` value here, so I can do it myself.

**Comment by n-rodriguez** [comment]
3dfc7b128d751fb7905e3fc1b919d81b9203ef295341ea324305fac22a8be8bc
