### ISSUE TITLE
Features don't include ssh any more

### ISSUE THREAD

**Issue by picman** [jbox-web/gitolite-rugged#12]
Why is `ssh` missing? The documentation says that it depends on the support of _ssh_ compiled into _libgit2_ library. However, _libgit2_ package is not installed on my system. I've just written a small test to compare the original and the current version of Rugged.
```ruby
require 'rugged'
puts Rugged::VERSION
puts Rugged.features.join("\n")
```
results from the original version:
```
$ ruby test.rb 
0.99.0
threads
https
ssh
```
and the current one:
```
$ ruby test.rb 
1.5.0.1
threads
https
```

**Comment by PowerKiKi** [comment]
@n-rodriguez, I assume this was your choice back then ?

**Comment by n-rodriguez** [comment]
> @n-rodriguez, I assume this was your choice back then ?

I think it's due to https://github.com/redmine-git-hosting/gitolite-rugged/commit/88b8626ccbe0ab590c7bb76ad1f9bae24ed73b91

See https://github.com/libgit2/rugged#use-the-system-provided-libgit2

**Comment by n-rodriguez** [comment]
> I've just written a small test to compare the original and the current version of Rugged.

"By default, Rugged builds and uses a bundled version of libgit2" so if you did `gem install rugged` to do your test, then you have installed the bundled library and so it works

When you install `rugged` as a gem dependency `libgit2` is not automatically built, see: https://github.com/libgit2/rugged#options

**Comment by picman** [comment]
From a common user's point of view, it simply doesn't work. Though, thank you for the explanation.

**Comment by PowerKiKi** [comment]
Would there be any way to improve the situation ? Can't we somehow declare that SSH must always be included ?
