### ISSUE TITLE
diffie-hellman-group-exchange-sha256 support

### ISSUE THREAD

**Issue by bs444** [jbox-web/gitolite-rugged#3]
It seems as though diffie-hellman-group-exchange-sha256 is not supported. Redmine Git Hosting is unable to make a localhost ssh connection (via gitolite-rugged) to a server that only supports this algorithm.

Recently, all of our organization's servers (Git servers included) were restricted to using only diffie-hellman-group-exchange-sha256 for ssh access.

i.e. `KexAlgorithms diffie-hellman-group-exchange-sha256` in the `sshd_config` file.

All other git and ssh clients survived this change (some had to be updated, such as PuTTY), however this change seems to have broken the Redmine Git Hosting plugin (or its gems) somewhere. I can't tell if it's an issue with gitolite-rugged, or libgit2/rugged.

git_hosting.log gives:

[ERROR] Invalid Gitolite Admin SSH Keys
[ERROR] Failed to start SSH session: Unable to exchange encryption keys

Regressing to older key exchange algorithms is unfortunately out of the question for our organization at this moment.

Redmine version                3.1.3.stable.15148
Ruby version                     2.2.3-p173 (2015-08-18) [x86_64-linux]
Rails version                     4.2.5.1
Redmine Git Hosting:       1.2-devel, which calls for...
gitolite-rugged                tag 1.2.0
Xitolite                              2.8.3

Is there an issue here? Or is it because the servers are too strict? I understand only supporting the one key exchange algorithm is not following the RFC's minimums, but supporting sha1 is out of the question here.

I'd appreciate if you could point me in the right direction.

**Comment by n-rodriguez** [comment]
> I can't tell if it's an issue with gitolite-rugged, or libgit2/rugged.

Hi! It comes from libgit2/rugged since gitolite-rugged is just a wrapper around it.

**Comment by n-rodriguez** [comment]
It seems to come from libssh2 : 
- https://www.libssh2.org/mail/libssh2-devel-archive-2009-04/0024.shtml
- https://github.com/wallix/pylibssh2/issues/26

**Comment by n-rodriguez** [comment]
I've made a test on my computer and it works so I would say it comes from `libssh2` :

Environment : 
- Archlinux
- libssh2 1.7.0-2
- openssh 7.2p2-2

`KexAlgorithms diffie-hellman-group-exchange-sha256` in the `sshd_config` file.

```
#!/usr/bin/env ruby

require 'net/ssh'

Net::SSH.start('localhost', 'nicolas', kex: 'diffie-hellman-group-exchange-sha256', verbose: :debug) do |ssh|
  output = ssh.exec!("hostname")
  puts output
end
```

```
D, [2016-07-21T23:28:40.930870 #9660] DEBUG -- net.ssh.transport.session[15a8254]: establishing connection to localhost:22
D, [2016-07-21T23:28:40.931401 #9660] DEBUG -- net.ssh.transport.session[15a8254]: connection established
I, [2016-07-21T23:28:40.931469 #9660]  INFO -- net.ssh.transport.server_version[15a39fc]: negotiating protocol version
D, [2016-07-21T23:28:40.931499 #9660] DEBUG -- net.ssh.transport.server_version[15a39fc]: local is `SSH-2.0-Ruby/Net::SSH_3.2.0 x86_64-linux'
D, [2016-07-21T23:28:40.937164 #9660] DEBUG -- net.ssh.transport.server_version[15a39fc]: remote is `SSH-2.0-OpenSSH_7.2'
I, [2016-07-21T23:28:40.938271 #9660]  INFO -- net.ssh.transport.algorithms[15a2e94]: sending KEXINIT
D, [2016-07-21T23:28:40.938487 #9660] DEBUG -- socket[15a3e70]: queueing packet nr 0 type 20 len 1524
D, [2016-07-21T23:28:40.938572 #9660] DEBUG -- socket[15a3e70]: sent 1528 bytes
D, [2016-07-21T23:28:40.938659 #9660] DEBUG -- socket[15a3e70]: read 856 bytes
D, [2016-07-21T23:28:40.938749 #9660] DEBUG -- socket[15a3e70]: received packet nr 0 type 20 len 852
I, [2016-07-21T23:28:40.938801 #9660]  INFO -- net.ssh.transport.algorithms[15a2e94]: got KEXINIT from server
I, [2016-07-21T23:28:40.938955 #9660]  INFO -- net.ssh.transport.algorithms[15a2e94]: negotiating algorithms
D, [2016-07-21T23:28:40.939064 #9660] DEBUG -- net.ssh.transport.algorithms[15a2e94]: negotiated:
* kex: diffie-hellman-group-exchange-sha256
* host_key: ssh-rsa
* encryption_server: aes128-ctr
* encryption_client: aes128-ctr
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: zlib@openssh.com
* compression_server: zlib@openssh.com
* language_client: 
* language_server: 
...
```

**Comment by n-rodriguez** [comment]
https://github.com/libssh2/libssh2/blob/7b9a9a782d69c097f69a1992023bde9e4ead046f/src/session.c#L726

https://github.com/libssh2/libssh2/issues/41#issuecomment-188828293

**Comment by bs444** [comment]
Thanks @n-rodriguez. That seems like it. Ubuntu 14.04 is back on[ v1.4.3-2](http://packages.ubuntu.com/trusty/libssh2-1).

What further steps are needed once I've got [version 1.7.0 installed via CMAKE](https://github.com/libssh2/libssh2/blob/7b9a9a782d69c097f69a1992023bde9e4ead046f/docs/INSTALL_CMAKE)?

**Comment by n-rodriguez** [comment]
`gem uninstall gitolite-rugged` then `bundle install`

**Comment by bs444** [comment]
Thank you. This fixes it. And since I had Passenger installed as a gem, I had to update and recompile it as well, otherwise Passenger would error out.
